export const CLEAR_ERROR = 'CLEAR_ERROR';
export const OPTIMISTIC_ADD_TODO = 'OPTIMISTIC_ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REPLACE_TODO = 'REPLACE_TODO';
export const REPLACE_TODOS = 'REPLACE_TODOS';
export const SHOW_ERROR = 'SHOW_ERROR';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const UPDATE_INPUT = 'UPDATE_INPUT';
