export const ADD_TODO_DATABASE_ID = 'ADD_TODO_DATABASE_ID';
export const OPTIMISTIC_ADD_TODO = 'OPTIMISTIC_ADD_TODO';
export const REPLACE_TODOS = 'REPLACE_TODOS';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const UPDATE_INPUT = 'UPDATE_INPUT';
